---

- hosts: all
  become: true
  
  tasks:
  - name: install apache 2 server
    apt:
      name: 
        - apache2
        - libapache2-mod-php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install apache 2 server
    yum:
      name: 
        - httpd
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Redhat", "Rocky", "CentOS"]
