---

- hosts: all
  become: true
  
  tasks:
  - name: update
    tags: always 
    apt:
      upgrade: dist      
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install apache 2 server
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Redhat", "Rocky", "CentOS"]


  - hosts: workstations
    become: true
    tasks:
      - name: install unzip
        package:
          - name: unzip


     - name: install terrofarm
       unachrive:
         src: https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
         dest: /usr/local/bin
         owner: root
         group: root
         mode: 0755
         remote_src: yes
      






- hosts: webserver
  become: true

  tasks:
  - name: install web server
    tags: ubuntu, apache, apache2
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"








  - name: install web sever
    tags: Rocky, httpd, apache
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: copy default, html file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true

  tasks:
  - name: install db server
    tags: mariadb, Rocky, db
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS", "Rocky", "Redhat"]

  - name: install maria db
    tags: mariadb, db, ubuntu
    apt:
      name: maria-server
      state: latest
    when: ansible_distribution == "ubuntu"
   
- hosts: file_server
  become: true

  tasks:
    - name: install samba server
      tags: samba
      package: 
        name: samba
        state: latest

